prophesee_genx320_node:
  ros__parameters:
    prophesee_genx320.qos.reliability: reliable
    prophesee_genx320.qos.history: keep_all
    prophesee_genx320.qos.depth: 10

detect_aruco_node:
  ros__parameters:
    prophesee_genx320.qos.reliability: reliable
    prophesee_genx320.qos.history: keep_all
    prophesee_genx320.qos.depth: 10
